"""Exhaustive technology & feature catalogue for MyHeath PFE reports."""


def write_tech_catalog(pdf, lang: str = "fr") -> None:
    if lang == "en":
        pdf.h2("3.2b Complete technology catalogue")
        pdf.p(
            "The following inventory lists every major technology used in MyHeath, "
            "grouped by layer. It is intended as a single reference for the oral defence."
        )
        pdf.h3("Backend (.NET)")
        pdf.bullet("ASP.NET Core 8 Web API — Controllers, middleware, hosting")
        pdf.bullet("C# 12 — static typing, records/DTOs, async/await")
        pdf.bullet("Dependency Injection (IServiceCollection) — Mongo, AES, JWT, Claude, Seed, Audit")
        pdf.bullet("JWT Bearer authentication — HMAC-SHA256, claim id + role, 7-day expiry")
        pdf.bullet("BCrypt.Net — password hashing, work factor 12")
        pdf.bullet("System.Security.Cryptography AES — AES-256-CBC, PKCS7, random IV")
        pdf.bullet("MongoDB.Driver — IMongoCollection, CamelCase + IgnoreExtraElements conventions")
        pdf.bullet("Swagger / OpenAPI — interactive docs at /swagger with Bearer scheme")
        pdf.bullet("HttpClient + ClaudeService — Anthropic Messages API")
        pdf.bullet("CORS policy from CLIENT_URL — multi-origin support")
        pdf.h3("Backend (Node parity, optional)")
        pdf.bullet("Node.js + Express — same /api contract for comparison")
        pdf.bullet("Mongoose ODM — users, logs, messages, plans, appointments")
        pdf.bullet("jsonwebtoken + bcryptjs + Node crypto AES helper")
        pdf.h3("Frontend")
        pdf.bullet("React 18 + Vite — SPA with fast HMR")
        pdf.bullet("React Router — public/private routes and role guards")
        pdf.bullet("Tailwind CSS — dashboard shell, responsive drawer")
        pdf.bullet("Axios — Bearer interceptor (localStorage myheath_token)")
        pdf.bullet("Recharts — cycle length bars, wellness trends")
        pdf.bullet("Context AuthContext — session user hydration via /auth/me")
        pdf.h3("Data & AI & Ops")
        pdf.bullet("MongoDB 7 (Docker) or MongoDB Atlas (cloud)")
        pdf.bullet("Anthropic Claude — coach plan, wellness tips, NL journal helpers")
        pdf.bullet("Docker multi-stage (sdk:8.0 -> aspnet:8.0) + docker-compose.dotnet.yml")
        pdf.bullet("Vercel — production SPA (https://heracare.vercel.app)")
        pdf.bullet("GitHub — public source https://github.com/salahEddine-Admou/MyHeath")
    else:
        pdf.h2("3.2b Catalogue technologique complet")
        pdf.p(
            "L'inventaire ci-dessous liste toutes les technologies majeures de MyHeath, "
            "par couche. Il sert de reference unique pour la soutenance."
        )
        pdf.h3("Backend (.NET)")
        pdf.bullet("ASP.NET Core 8 Web API — Controllers, middleware, hosting")
        pdf.bullet("C# 12 — typage statique, DTO, async/await")
        pdf.bullet("Injection de dependances — Mongo, AES, JWT, Claude, Seed, Audit")
        pdf.bullet("JWT Bearer — HMAC-SHA256, claims id + role, expiration 7 jours")
        pdf.bullet("BCrypt.Net — hachage mots de passe (cost 12)")
        pdf.bullet("AES-256-CBC (System.Security.Cryptography) — IV aleatoire, PKCS7")
        pdf.bullet("MongoDB.Driver — conventions camelCase + IgnoreExtraElements")
        pdf.bullet("Swagger / OpenAPI — /swagger avec schema Bearer")
        pdf.bullet("HttpClient + ClaudeService — Anthropic Messages API")
        pdf.bullet("CORS depuis CLIENT_URL — origines multiples")
        pdf.h3("Backend Node (parite optionnelle)")
        pdf.bullet("Node.js + Express — meme contrat /api")
        pdf.bullet("Mongoose — users, logs, messages, plans, RDV")
        pdf.bullet("jsonwebtoken + bcryptjs + helper crypto AES")
        pdf.h3("Frontend")
        pdf.bullet("React 18 + Vite — SPA")
        pdf.bullet("React Router — routes publiques/privees et gardes de role")
        pdf.bullet("Tailwind CSS — shell dashboard, drawer mobile")
        pdf.bullet("Axios — interceptor Bearer (localStorage myheath_token)")
        pdf.bullet("Recharts — graphiques cycle et tendances")
        pdf.bullet("AuthContext — hydratation session via /auth/me")
        pdf.h3("Donnees, IA et Ops")
        pdf.bullet("MongoDB 7 (Docker) ou MongoDB Atlas")
        pdf.bullet("Anthropic Claude — coach, wellness, aides journal")
        pdf.bullet("Docker multi-stage + docker-compose.dotnet.yml")
        pdf.bullet("Vercel — SPA production (https://heracare.vercel.app)")
        pdf.bullet("GitHub — https://github.com/salahEddine-Admou/MyHeath")


def write_features_catalog(pdf, lang: str = "fr") -> None:
    if lang == "en":
        pdf.h2("5.8 Complete feature catalogue (all roles)")
        pdf.p(
            "MyHeath is not a thin CRUD demo. The following catalogue enumerates every "
            "user-facing and administrative feature implemented in the product."
        )
        pdf.h3("Public / authentication")
        pdf.bullet("Marketing landing page with product value proposition")
        pdf.bullet("Register (patient|doctor) and Login with JWT session")
        pdf.bullet("Demo credentials pre-filled for jury convenience")
        pdf.bullet("Role-aware redirect after login (patient / doctor / admin)")
        pdf.h3("Patient — women's & men's health")
        pdf.bullet("Dashboard: cycle summary cards, anomaly alerts, quick actions")
        pdf.bullet("Daily suivi journal: sleep, stress, mood, activity, water, recovery")
        pdf.bullet("Predictive wellness score 0-100 with qualitative label")
        pdf.bullet("Period calendar: flow, symptoms, pain scale, phase visualisation")
        pdf.bullet("Cycle insights: average length, ovulation window, next period, anomalies")
        pdf.bullet("Diabetes care: fasting/post-meal glucose, medication adherence overview")
        pdf.bullet("Encrypted health record: allergies, treatments, clinical notes")
        pdf.bullet("Medication reminders: schedules and daily dose tracking")
        pdf.bullet("Appointments: book video / chat / in-person with a doctor")
        pdf.bullet("Encrypted telemedicine chat with assigned clinician")
        pdf.bullet("AI Coach (Claude): coach plan, wellness tips, non-diagnostic disclaimer")
        pdf.bullet("Doctor assignment from directory of clinicians")
        pdf.h3("Doctor")
        pdf.bullet("Doctor dashboard with assigned-patient focus")
        pdf.bullet("Encrypted messaging with patients")
        pdf.bullet("Appointment list and status management")
        pdf.bullet("Access path to patient clinical context within RBAC rules")
        pdf.h3("Administrator")
        pdf.bullet("Overview KPIs and estimated MRR")
        pdf.bullet("User CRUD, activate/deactivate accounts")
        pdf.bullet("Subscription plans FREE / CARE / PREMIUM")
        pdf.bullet("Assign or cancel user subscriptions")
        pdf.bullet("Audit trail of sensitive admin actions")
        pdf.h3("Cross-cutting platform features")
        pdf.bullet("In-app notifications (e.g. new appointment)")
        pdf.bullet("Swagger API explorer for jury and developers")
        pdf.bullet("Docker Compose one-command local stack")
        pdf.bullet("SeedService demo users and plans at startup")
        pdf.bullet("Dual-backend switch via VITE_API_URL (Node or .NET)")
    else:
        pdf.h2("5.8 Catalogue fonctionnel complet (tous roles)")
        pdf.p(
            "MyHeath n'est pas un simple CRUD. Le catalogue suivant enumere chaque "
            "fonctionnalite utilisateur et administrative implementee dans le produit."
        )
        pdf.h3("Public / authentification")
        pdf.bullet("Landing marketing avec proposition de valeur")
        pdf.bullet("Inscription (patient|doctor) et connexion JWT")
        pdf.bullet("Comptes demo pre-remplis pour le jury")
        pdf.bullet("Redirection selon le role apres login")
        pdf.h3("Patient — sante femme et homme")
        pdf.bullet("Dashboard: resume cycle, alertes d'anomalies, actions rapides")
        pdf.bullet("Journal de suivi: sommeil, stress, humeur, activite, eau, recuperation")
        pdf.bullet("Score predictif 0-100 avec label qualitatif")
        pdf.bullet("Calendrier periodes: flux, symptomes, douleur, phase")
        pdf.bullet("Insights cycle: moyenne, ovulation, prochaine regle, anomalies")
        pdf.bullet("Diabete: glycemie a jeun/postprandiale, adherence medicamenteuse")
        pdf.bullet("Dossier medical chiffre: allergies, traitements, notes")
        pdf.bullet("Rappels medicaments: horaires et suivi des prises")
        pdf.bullet("RDV: video / chat / presentiel avec un medecin")
        pdf.bullet("Chat telemedecine chiffre avec medecin assigne")
        pdf.bullet("Coach IA Claude: plan, tips, disclaimer non diagnostique")
        pdf.bullet("Assignation d'un medecin depuis l'annuaire")
        pdf.h3("Medecin")
        pdf.bullet("Dashboard centre sur les patients assignes")
        pdf.bullet("Messagerie chiffree patient-medecin")
        pdf.bullet("Liste et gestion des rendez-vous")
        pdf.bullet("Acces au contexte clinique dans les limites RBAC")
        pdf.h3("Administrateur")
        pdf.bullet("Overview KPI et MRR estime")
        pdf.bullet("CRUD utilisateurs, activation/desactivation")
        pdf.bullet("Plans FREE / CARE / PREMIUM")
        pdf.bullet("Assignation / annulation d'abonnements")
        pdf.bullet("Journal d'audit des actions sensibles")
        pdf.h3("Fonctions transverses")
        pdf.bullet("Notifications in-app (ex. nouveau RDV)")
        pdf.bullet("Swagger pour le jury et les developpeurs")
        pdf.bullet("Docker Compose en une commande")
        pdf.bullet("SeedService (comptes et plans demo)")
        pdf.bullet("Basculer Node/.NET via VITE_API_URL")
